//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplyLikesOrDislike
    {
        public int Id { get; set; }
        public int ReplyId { get; set; }
        public int Videoid { get; set; }
        public string Username { get; set; }
        public bool LikeOrDislike { get; set; }
    
        public virtual Reply Reply { get; set; }
    }
}
