//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.Comments = new HashSet<Comment>();
            this.VideoLikesOrDislikes = new HashSet<VideoLikesOrDislike>();
        }
    
        public int Id { get; set; }
        public int CreatorId { get; set; }
        public string VideoName { get; set; }
        public string Description { get; set; }
        public string VideoURL { get; set; }
        public string ThumbnailURL { get; set; }
        public int Likes { get; set; }
        public int Dislikes { get; set; }
        public int Views { get; set; }
        public string CreatorPhotoUrl { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatorName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoLikesOrDislike> VideoLikesOrDislikes { get; set; }
        public virtual Video Videos1 { get; set; }
        public virtual Video Video1 { get; set; }
    }
}
